filters:
    - true

# The message to post to the closed PR.
commentBody: |
  Thanks for your contribution! Unfortunately, we don't use GitHub pull requests.

# Whether or not to add a label to the closed PR.
addLabel: false
