name: PR Closer

on:
  pull_request:
    types: [opened, reopened]


jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull
        uses: peter-evans/close-fork-pulls@v2
        with:
          comment: |
            Sorry. Pull requests are not accepted for this repository.
            Auto-closing this pull request.
